import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { CheckCircle2, ChevronLeft, ChevronRight, FileUp, Loader2, ShieldCheck, Upload, X } from 'lucide-react'
import { useAuth, type RegistrationInput } from '../../contexts/AuthContext'

type Category = RegistrationInput['category']
type FormState = Omit<RegistrationInput, 'uploadedDocs'> & { confirmPassword: string; uploadedDocs: RegistrationInput['uploadedDocs'] }
const blank = (category: Category): FormState => ({ category, email: '', password: '', confirmPassword: '', name: '', phone: '', department: '', employeeId: '', designation: '', region: '', companyName: '', contactPerson: '', companyAddress: '', gstNumber: '', panNumber: '', companyWebsite: '', uploadedDocs: [] })
function Field({ label, value, onChange, type = 'text', required }: { label: string; value: string | undefined; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-neutral-700">{label}{required && ' *'}</span><input required={required} type={type} value={value ?? ''} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-neutral-200 bg-white px-3.5 py-2.5 text-sm outline-none transition focus:border-brand-500 focus:ring-4 focus:ring-brand-100" /></label> }

export default function RegistrationWizard({ category }: { category: Category }) {
  const navigate = useNavigate(); const { submitRegistration, logout } = useAuth(); const [step, setStep] = useState(1); const [form, setForm] = useState<FormState>(() => blank(category)); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [uploading, setUploading] = useState(false); const [requestId, setRequestId] = useState<string | null>(null)
  const employee = category === 'EMPLOYEE'; const title = employee ? 'POWERGRID Employee' : 'Contractor / Vendor'; const update = (key: keyof FormState, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const next = () => { const required = employee ? [form.name, form.employeeId, form.email, form.phone, form.department, form.designation] : [form.companyName, form.contactPerson, form.email, form.phone, form.companyAddress, form.gstNumber, form.panNumber]; if (step === 1 && required.some((value) => !value?.trim())) return setError('Complete all required fields to continue.'); if (step === 1 && form.password.length < 8) return setError('Use a password of at least 8 characters.'); if (step === 1 && form.password !== form.confirmPassword) return setError('Passwords do not match.'); setError(''); setStep((current) => Math.min(current + 1, 4)) }
  const upload = async (file: File) => { const cloud = import.meta.env.VITE_CLOUDINARY_CLOUD_NAME as string | undefined; const preset = import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET as string | undefined; if (!cloud || !preset) return setError('Document uploads require Cloudinary configuration in frontend/.env.'); setUploading(true); setError(''); try { const body = new FormData(); body.append('file', file); body.append('upload_preset', preset); body.append('folder', 'powergrid/registration'); const response = await fetch(`https://api.cloudinary.com/v1_1/${cloud}/auto/upload`, { method: 'POST', body }); if (!response.ok) throw new Error('Cloudinary could not accept this file.'); const data = await response.json() as { secure_url: string; public_id: string; bytes: number }; setForm((current) => ({ ...current, uploadedDocs: [...current.uploadedDocs, { name: file.name, url: data.secure_url, publicId: data.public_id, type: file.type || 'application/octet-stream', size: data.bytes }] })) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Upload failed.') } finally { setUploading(false) } }
  const submit = async () => { setSubmitting(true); setError(''); try { const name = employee ? form.name : form.contactPerson; const id = await submitRegistration({ ...form, name: name ?? '', phone: form.phone ?? '', uploadedDocs: form.uploadedDocs }); setRequestId(id); await logout(); setStep(5) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Registration could not be submitted.') } finally { setSubmitting(false) } }
  if (step === 5) return <div className="text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-brand-700" /><h1 className="mt-4 text-2xl font-semibold text-neutral-900">Registration submitted</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-neutral-600">An administrator will review your request before activating your account.</p>{requestId && <p className="mt-4 rounded-xl bg-neutral-50 p-3 font-mono text-xs text-neutral-600">Request ID: {requestId}</p>}<div className="mt-7 flex justify-center gap-3"><button onClick={() => navigate('/login')} className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Return to login</button><a href="mailto:administrator@powergrid.in" className="rounded-xl border border-neutral-200 px-4 py-2.5 text-sm font-semibold text-neutral-700">Contact administrator</a></div></div>
  return <div><div className="mb-7 flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-brand-700">Request access</p><h1 className="mt-1 text-2xl font-semibold text-neutral-900">{title}</h1></div><p className="text-xs text-neutral-500">Step {step} of 4</p></div><div className="mb-7 h-1.5 overflow-hidden rounded-full bg-neutral-200"><div className="h-full bg-brand-600 transition-all" style={{ width: `${step * 25}%` }} /></div>
  {step === 1 && <div className="grid gap-4 sm:grid-cols-2">{employee ? <><Field label="Full name" required value={form.name} onChange={(v) => update('name', v)} /><Field label="Employee ID" required value={form.employeeId} onChange={(v) => update('employeeId', v)} /><Field label="Official email" required type="email" value={form.email} onChange={(v) => update('email', v)} /><Field label="Phone number" required value={form.phone} onChange={(v) => update('phone', v)} /><Field label="Department" required value={form.department} onChange={(v) => update('department', v)} /><Field label="Designation" required value={form.designation} onChange={(v) => update('designation', v)} /><Field label="Region" value={form.region} onChange={(v) => update('region', v)} /></> : <><Field label="Company name" required value={form.companyName} onChange={(v) => update('companyName', v)} /><Field label="Authorized person" required value={form.contactPerson} onChange={(v) => update('contactPerson', v)} /><Field label="Official email" required type="email" value={form.email} onChange={(v) => update('email', v)} /><Field label="Phone number" required value={form.phone} onChange={(v) => update('phone', v)} /><Field label="GST number" required value={form.gstNumber} onChange={(v) => update('gstNumber', v)} /><Field label="PAN number" required value={form.panNumber} onChange={(v) => update('panNumber', v)} /><Field label="Company website" value={form.companyWebsite} onChange={(v) => update('companyWebsite', v)} /><Field label="Office address" required value={form.companyAddress} onChange={(v) => update('companyAddress', v)} /></>}<Field label="Password" required type="password" value={form.password} onChange={(v) => update('password', v)} /><Field label="Confirm password" required type="password" value={form.confirmPassword} onChange={(v) => update('confirmPassword', v)} /></div>}
  {step === 2 && <div><div className="rounded-2xl border border-dashed border-brand-300 bg-brand-50/40 p-7 text-center"><FileUp className="mx-auto h-8 w-8 text-brand-700" /><p className="mt-3 text-sm font-semibold text-neutral-900">Supporting documents</p><p className="mt-1 text-xs text-neutral-600">Upload certificates and identity documents directly to Cloudinary.</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-brand-700 shadow-sm ring-1 ring-brand-100"><Upload className="h-4 w-4" />{uploading ? 'Uploading...' : 'Choose file'}<input type="file" className="hidden" disabled={uploading} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file) }} /></label></div><div className="mt-4 space-y-2">{form.uploadedDocs.map((document) => <div key={document.publicId} className="flex items-center justify-between rounded-xl border border-neutral-200 px-3 py-2.5 text-sm"><span className="truncate">{document.name}</span><button type="button" onClick={() => setForm((current) => ({ ...current, uploadedDocs: current.uploadedDocs.filter((item) => item.publicId !== document.publicId) }))} className="text-neutral-500 hover:text-red-600"><X className="h-4 w-4" /></button></div>)}</div></div>}
  {step === 3 && <div className="space-y-4"><div className="rounded-2xl bg-neutral-50 p-5"><h2 className="font-semibold text-neutral-900">Review your request</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-neutral-500">Category</dt><dd className="font-medium">{title}</dd></div><div><dt className="text-neutral-500">Official email</dt><dd className="font-medium">{form.email}</dd></div><div><dt className="text-neutral-500">Applicant</dt><dd className="font-medium">{employee ? form.name : form.contactPerson}</dd></div><div><dt className="text-neutral-500">Documents</dt><dd className="font-medium">{form.uploadedDocs.length} uploaded</dd></div></dl></div><div className="flex gap-3 rounded-xl border border-brand-100 bg-brand-50 p-4 text-sm text-brand-900"><ShieldCheck className="h-5 w-5 shrink-0" />Your password is securely hashed before it is stored and is never shown to administrators.</div></div>}
  {step === 4 && <div className="py-5 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-brand-700" /><h2 className="mt-3 text-lg font-semibold">Ready to submit</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-neutral-600">Your account will remain pending until the registration review is completed.</p></div>}{error && <p className="mt-4 rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<div className="mt-7 flex items-center justify-between"><button onClick={() => step === 1 ? navigate('/register') : setStep((current) => current - 1)} className="inline-flex items-center gap-1 text-sm font-medium text-neutral-600"><ChevronLeft className="h-4 w-4" />Back</button>{step < 4 ? <button onClick={next} className="inline-flex items-center gap-1 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white">Continue<ChevronRight className="h-4 w-4" /></button> : <button disabled={submitting} onClick={() => void submit()} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{submitting && <Loader2 className="h-4 w-4 animate-spin" />}{submitting ? 'Submitting...' : 'Submit request'}</button>}</div></div>
}
