import { Router } from "express";
import { authenticate, validate } from "../middleware";
import { asyncHandler } from "../utils";
import { authController } from "../controllers";
import { loginSchema, registerUserSchema } from "../validators";
const router = Router();
router.post("/register", validate(registerUserSchema), asyncHandler(authController.register.bind(authController)));
router.post("/login", validate(loginSchema), asyncHandler(authController.login.bind(authController)));
router.post("/login/failure", asyncHandler(authController.recordLoginFailure.bind(authController)));
router.post("/unlock/:id", authenticate, asyncHandler(authController.unlockUser.bind(authController)));
export default router;
